services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  pysorts-backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.backend
    container_name: pysorts-backend
    depends_on:
      - redis
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - .:/app
      - ./.venv:/app/.venv:cached

  pysorts-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: pysorts-frontend
    depends_on:
      - pysorts-backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - .:/app

networks:
  app-network:
    driver: bridge
