name: Backend Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install uv
        run: |
          apt install uv

      - name: Install dependencies
        run: |
          uv pip install ".[dev]"

      - name: Run tests
        run: |
          pytest --maxfail=5 --disable-warnings --junitxml=test-results.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.xml
